### ISSUE TITLE
Getting started guide

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/rancher-turtles-docs#8]
We need to create a getting started guide so that users are able to use Rancher Turtles.

This epic will cover the following:

- [x] rancher-sandbox/rancher-turtles-docs#7 
- [x] rancher-sandbox/rancher-turtles-docs#9
- [x] rancher-sandbox/rancher-turtles-docs#6
- [x] rancher-sandbox/rancher-turtles-docs#5
- [x] https://github.com/rancher-sandbox/rancher-turtles-docs/issues/17
- [x] rancher-sandbox/rancher-turtles#130
